import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideNav from "@/components/shared/side-nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Code Notes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="min-h-screen">
          <div className="flex">
            <SideNav />
            <div className="flex justify-center items-center h-screen w-screen bg-black">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
